export const LOGIN_ROUTE = '/auth/login'
export const REGISTER_ROUTE = '/auth/register'

export const ORDERS_ROUTE = '/orders'
export const PRODUCTS_ROUTE = '/products'
export const CATEGORIES_ROUTE = '/categories'
export const CITIES_ROUTE = '/cities'
export const BRANDS_ROUTE = '/brands'
export const PROTOCOLS_ROUTE = '/protocols'
export const BANNERS_ROUTE = '/banners'
export const SEMINARS_ROUTE = '/seminars'
export const PROMOCODE_ROUTE = '/promocode'
